### ISSUE TITLE
Bug in auth header

### ISSUE THREAD

**Issue by agrzegorczyk-leonsoftware** [newrelic/newrelic-fluentd-output#11]
Hi,
during tests of the plugin, we can't authorize via license key, with error 400. After some investigation I think, there is an error:
https://github.com/newrelic/newrelic-fluentd-output/blob/93ad4007964b4653d52a633cb48eb2bac3e53742/lib/fluent/plugin/out_newrelic.rb#L59
According to Log API docs ( https://docs.newrelic.com/docs/logs/new-relic-logs/log-api/introduction-log-api ), this should be `X-License-Key` instead `X-License_key`.

regards,
Adam Grzegorczyk
Leon Software

**Comment by bmcfeely** [comment]
Thank you, @agrzegorczyk-leonsoftware! Apologies for the trouble. We have fixed the issue and pushed the changes here. Please use version `1.1.4`: https://rubygems.org/gems/fluent-plugin-newrelic/versions/1.1.4

Side note: we currently have a bit of an unusual workflow -- all development is done in an internal New Relic repo, and we mirror the latest changes here. So if you're wondering why you didn't see a PR here, that's why. :) We're working on a more public-friendly workflow.

**Comment by agrzegorczyk-leonsoftware** [comment]
Thanks for fast reaction, works great now even with Licence Key :)
